services:
  sample-data:
    environment:
      PIRO_BOOTSTRAP_DB: "false"
      PIRO_FORCE_RESET: "false"
      PIRO_LOAD_SAMPLE_DATA: "false"

  api:
    environment:
      MSSQL_SERVER: 10.88.62.23,52793
      MSSQL_DB: PIRO_DEV
      MSSQL_USER: piro_migrations
      MSSQL_PASSWORD: Goodd@ytoy()u
      ACCESS_TOKEN_TEST_USER: roberts10
      SOLR_URL: https://dev-piro.ccf.org:8989/solr
      SOLR_USER_NAME: piro-user
      SOLR_USER_PASSWORD: "i1CHuM%JQPyme*"
