services:
  sample-data:
    environment:
      PIRO_BOOTSTRAP_DB: "false"
      PIRO_FORCE_RESET: "false"
      PIRO_LOAD_SAMPLE_DATA: "false"

  api:
    environment:
      MSSQL_SERVER: CC-CLEVSQL10A01/SQLT10A1
      MSSQL_DB: PIRO_DEV
      MSSQL_USER: piro_migrations
      MSSQL_PASSWORD: PiroUser32026!
