from db.base_class import Base
from sqlalchemy import Boolean, Column, DateTime, Integer, String


class VCase(Base):
    __tablename__ = "V_Case"
    CaseId = Column(Integer, primary_key=True, index=True)
    RefRequisitionKey = Column(String, nullable=False)
    SpecimenYear = Column(Integer, nullable=False)
    CaseNumber = Column(String, nullable=False)
    AccessionDate = Column(DateTime(timezone=True), nullable=False)
    ReceiveDate = Column(DateTime(timezone=True), nullable=False)
    OverdueDate = Column(DateTime(timezone=True), nullable=False)
    CollectionDate = Column(DateTime(timezone=True), nullable=False)
    SignoutDate = Column(DateTime(timezone=True), nullable=False)
    PatientName = Column(String, nullable=False)

    PatientDOB = Column(DateTime, nullable=False)
    PatientEpi = Column(String, nullable=False)
    PatientMrn = Column(String, nullable=False)
    PatientLanguage = Column(String, nullable=False)
    PatientEthnicity = Column(String, nullable=False)
    PatientGender = Column(String, nullable=False)
    PatientDeathDate = Column(DateTime, nullable=False)
    PatientIsDeceased = Column(Boolean, nullable=False)
    PatientRace = Column(String, nullable=False)
    PatientCity = Column(String, nullable=False)
    PatientState = Column(String, nullable=False)
    PatientCountry = Column(String, nullable=False)
    Hospital = Column(String, nullable=False)
    Region = Column(String, nullable=False)
    CaseStatus = Column(String, nullable=False)
    CaseType = Column(String, nullable=False)
    CaseTypeCategory = Column(String, nullable=False)
    ReviewType = Column(String, nullable=False)
    Specialty = Column(String, nullable=False)
    SpecialtyCode = Column(String, nullable=False)
    SpecialtyCategory = Column(String, nullable=False)
    CasePatientAge = Column(String, nullable=False)
    CasePatientAgeYears = Column(Integer, nullable=False)
    AnnotationMalignant = Column(String, nullable=False)
    IsEpicMigrated = Column(Boolean, nullable=False)
    IsEpic = Column(Boolean, nullable=False)
    IsCopath = Column(Boolean, nullable=False)
    CreateDate = Column(DateTime(timezone=True))
    UpdateDate = Column(DateTime(timezone=True), nullable=True)
    IsConcentriq = Column(Boolean, nullable=False)
    CaseConcentriqId = Column(Integer, nullable=False)
