export const environment = {
  production: true,
  apiBaseUrl: '<your api url>',
  recordsPerPage: 10,
  debounceTime: 1000,
  filterDataUrl: 'solr/filterdata',
  searchUrl: 'solr/search',
  facetUrl: 'solr/facet',
  lastdataupdatedUrl: 'solr/lastdataupdated',
  suggestStaffUrl: 'solr/suggeststaff',
  suggestCommentUrl: 'solr/suggestcomment',
  suggestCaseUrl: 'solr/suggestcase',
  caseinfo: 'case/caseinfo',
  saveaivoteUrl: 'annotation/createfeedback',
  aifeedbackCaseUrl: 'annotation/getfeedback',
  aifeedbackDataUrl: 'annotation/getfeedbackdata',
  aifeedbackAllUrl: 'annotation/getfeedbackall',
  aicaseauditlUrl: 'annotation/getaudit',
  isPendingAiFeedbackReviewUrl: 'annotation/ispendingreview',
  markreviewedUrl: 'annotation/updatefeedback',
  tagUrl: 'tagcase/tags',
  textCommentsUrl: 'casecomment/text',
  epicCommentsUrl: 'casecomment/epic',
  coPathCommentsUrl: 'casecomment/copath',
  synopticCommentsUrl: 'casecomment/synopticreport',
  annotationConfigUrl: 'case/annotationconfig',
  getAttestationUrl: "token/attest",
  saveAttestationUrl: "token/saveattest",
  errorExceptionMessage: 'Error during data fetch',
  accessExceptionMessage: 'Permission denied for the request'
};