/****** Object:  Table [SSIS_CaseData]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CaseData](
	[CASE_ID] [bigint] NOT NULL,
	[CASE_ACCESSION_DTTM] [datetime] NULL,
	[CASE_RECEIVED_DTTM] [datetime] NULL,
	[CASE_OVERDUE_DTTM] [datetime] NULL,
	[CASE_PAT_ID] [varchar](18) NULL,
	[CASE_LAB_ID] [varchar](18) NULL,
	[CASE_COLL_DTTM] [datetime] NULL,
	[CASE_SIGNOUT_DTTM] [datetime] NULL,
	[CASE_TASK_ADD_DTTM] [datetime] NULL,
	[INSTANT_PAT_ASSOC_UTC_DTTM] [datetime] NULL,
	[CASE_SUBSPECIALTY_C] [decimal](38, 0) NULL,
	[PAT_ASSOC_DTTM] [datetime] NULL,
	[CASE_TYPE_ID] [varchar](18) NULL,
	[CASE_NUM] [varchar](254) NULL,
	[AP_CASE_STATUS_C] [decimal](38, 0) NULL,
	[LAST_TASK_ADDED_UTC_DTTM] [datetime] NULL,
	[CASE_ACCESSION_UTC_DTTM] [datetime] NULL,
 CONSTRAINT [PK_SSIS_CaseData] PRIMARY KEY CLUSTERED 
(
	[CASE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SSIS_CaseData_AP_CASE_STATUS_CD]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SSIS_CaseData_AP_CASE_STATUS_CD] ON [SSIS_CaseData]
(
	[AP_CASE_STATUS_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SSIS_CaseData_CASE_LAB_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SSIS_CaseData_CASE_LAB_ID] ON [SSIS_CaseData]
(
	[CASE_LAB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SSIS_CaseData_CASE_SUBSPECIALTY_CD]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SSIS_CaseData_CASE_SUBSPECIALTY_CD] ON [SSIS_CaseData]
(
	[CASE_SUBSPECIALTY_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SSIS_CaseData_CASE_TYPE_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SSIS_CaseData_CASE_TYPE_ID] ON [SSIS_CaseData]
(
	[CASE_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SSIS_CaseData_K_PAT_KEY]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SSIS_CaseData_K_PAT_KEY] ON [SSIS_CaseData]
(
	[CASE_PAT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SSIS_CaseData_K_REQUISITION_KEY]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SSIS_CaseData_K_REQUISITION_KEY] ON [SSIS_CaseData]
(
	[CASE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CaseFlag]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CaseFlag](
	[CASE_FLAGS_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_CaseFlag] PRIMARY KEY CLUSTERED 
(
	[CASE_FLAGS_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CaseStaff]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CaseStaff](
	[K_REQUISITION_KEY] [decimal](38, 0) NOT NULL,
	[K_EMPLOYEE_KEY] [varchar](50) NULL,
	[LINE] [int] NULL,
	[RESPONSIBLE_ROLE_DESC] [varchar](300) NULL,
	[RESPONSIBLE_DTTM] [datetime] NULL
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CaseStatus]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CaseStatus](
	[AP_CASE_STATUS_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_CaseStatus] PRIMARY KEY CLUSTERED 
(
	[AP_CASE_STATUS_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [SSIS_CaseType]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CaseType](
	[LAB_ID] [varchar](18) NOT NULL,
	[CM_PHY_OWNER_ID] [varchar](25) NULL,
	[CM_LOG_OWNER_ID] [varchar](25) NULL,
	[ID_PIECE_FORMAT_C] [decimal](38, 0) NULL,
	[DELIM_PREC_SLD] [varchar](10) NULL,
	[DELIM_PREC_SPEC] [varchar](10) NULL,
	[AP_WORKLIST_TYPE_C] [decimal](38, 0) NULL,
	[CASE_TYPE_NAME] [varchar](254) NULL,
	[AP_USE_HISTOLOGY_YN] [varchar](1) NULL,
	[CASE_EXPECTED_LEN] [decimal](38, 0) NULL,
	[CASE_EXPECTED_LEN_C] [decimal](38, 0) NULL,
	[TYPE_CASE_C] [decimal](38, 0) NULL,
	[AP_REL_RPT_SET_ID] [bigint] NULL,
	[AP_USE_IN_BASKET_YN] [varchar](1) NULL,
	[REPORT_NAME] [varchar](254) NULL,
	[AP_QA_RPT_SET_ID] [bigint] NULL,
	[MED_CYTO_WORKFLOW_C] [decimal](38, 0) NULL,
	[AP_CHRG_REVIEW_YN] [varchar](1) NULL,
	[SKIP_ON_SOURCE_YN] [varchar](1) NULL,
	[ALLOW_MANUAL_NUM_C] [decimal](38, 0) NULL,
	[AP_CHRG_REVIEW_C] [decimal](38, 0) NULL,
	[BELONGS_TO_LAB_ID] [varchar](18) NULL,
	[TYPE_CASE] [varchar](254) NULL,
	[WORKLIST_TYPE] [varchar](254) NULL,
 CONSTRAINT [PK_SSIS_CaseType] PRIMARY KEY CLUSTERED 
(
	[LAB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CaseTypeCategory]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CaseTypeCategory](
	[TYPE_CASE_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_CaseTypeCategory] PRIMARY KEY CLUSTERED 
(
	[TYPE_CASE_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CommentPlainText]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CommentPlainText](
	[RESULT_ID] [decimal](38, 0) NULL,
	[GROUP_LINE] [int] NULL,
	[VALUE_LINE] [int] NULL,
	[COMP_NAME] [varchar](1000) NULL,
	[COMMENT_TYPE] [varchar](100) NULL,
	[COMPONENT_ID] [decimal](38, 0) NULL,
	[COMPONENT_INST] [datetime] NULL,
	[SPECIMENS_ID] [decimal](38, 0) NULL,
	[REQUISITION_ID] [decimal](38, 0) NULL,
	[MULT_LN_VAL_STORAGE] [varchar](max) NULL,
	[RANK_RES_GROUP] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_SSIS_CommentPlainText_CommentType]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentPlainText_CommentType] ON [SSIS_CommentPlainText]
(
	[COMMENT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_SSIS_CommentPlainText_CompName]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentPlainText_CompName] ON [SSIS_CommentPlainText]
(
	[COMP_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_SSIS_CommentPlainText_REQUISITION_CommentType_Comp]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentPlainText_REQUISITION_CommentType_Comp] ON [SSIS_CommentPlainText]
(
	[REQUISITION_ID] ASC,
	[COMMENT_TYPE] ASC,
	[COMP_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_CommentPlainText_REQUISITION_COMPONENT_GROUP_VALUE]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentPlainText_REQUISITION_COMPONENT_GROUP_VALUE] ON [SSIS_CommentPlainText]
(
	[REQUISITION_ID] ASC,
	[COMPONENT_ID] ASC,
	[GROUP_LINE] ASC,
	[VALUE_LINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_CommentPlainText_REQUISITION_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentPlainText_REQUISITION_ID] ON [SSIS_CommentPlainText]
(
	[REQUISITION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_CommentPlainText_RESULT_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentPlainText_RESULT_ID] ON [SSIS_CommentPlainText]
(
	[RESULT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Table [SSIS_CommentRTFText]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CommentRTFText](
	[ORDER_ID] [decimal](38, 0) NULL,
	[RESULT_ID] [decimal](38, 0) NULL,
	[CONTACT_DATE_REAL] [decimal](38, 5) NULL,
	[LINE_RTF_CMT] [int] NULL,
	[RTF_VAL_START_LINE] [decimal](38, 0) NULL,
	[RTF_VAL_END_LINE] [decimal](38, 0) NULL,
	[LINE_RES_SPE] [int] NULL,
	[CONTACT_DATE] [datetime] NULL,
	[COMP_NAME] [varchar](1000) NULL,
	[COMMENT_TYPE] [varchar](100) NULL,
	[RTF_VAL_CMT] [varchar](max) NULL,
	[RES_ORDER_ID] [decimal](38, 0) NULL,
	[RES_SPECIMEN_ID] [decimal](38, 0) NULL,
	[RES_SPECIMEN] [varchar](1000) NULL,
	[SPECIMENS_ID] [decimal](38, 0) NULL,
	[COMP_RES_UTC_DTTM] [datetime] NULL,
	[COMPONENT_ID] [decimal](38, 0) NULL,
	[REQUISITION_ID] [decimal](38, 0) NULL,
	[RANK_RES_DB_MAIN] [decimal](38, 0) NULL,
	[RANK_RES_SPECIMENS] [decimal](38, 0) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_SSIS_CommentRTFText_CommentType]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentRTFText_CommentType] ON [SSIS_CommentRTFText]
(
	[COMMENT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_CommentRTFText_REQUISITION_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentRTFText_REQUISITION_ID] ON [SSIS_CommentRTFText]
(
	[REQUISITION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_CommentRTFText_RESULT_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentRTFText_RESULT_ID] ON [SSIS_CommentRTFText]
(
	[RESULT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_CommentRTFText_RESULT_LINE]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_CommentRTFText_RESULT_LINE] ON [SSIS_CommentRTFText]
(
	[RESULT_ID] ASC,
	[LINE_RES_SPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CommentSynopticCaseLevel]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CommentSynopticCaseLevel](
	[SYNOPTIC_ID] [decimal](38, 0) NULL,
	[SYNOPIC_LINE] [int] NULL,
	[SPECIMEN_ID] [decimal](38, 0) NULL,
	[K_SPECIMEN_KEY] [decimal](38, 0) NULL,
	[SPECIMEN_NUM] [varchar](1000) NULL,
	[K_REQUISITION_KEY] [decimal](38, 0) NULL,
	[CASE_NUM] [varchar](1000) NULL,
	[SPECIMEN_LIST] [varchar](1000) NULL,
	[RECORD_CREATION_DT] [datetime] NULL,
	[IS_SPECIMEN_LEVEL] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Index [IX_SSIS_CommentSynopticCaseLevel_SYNOPTIC_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IX_SSIS_CommentSynopticCaseLevel_SYNOPTIC_ID] ON [SSIS_CommentSynopticCaseLevel]
(
	[SYNOPTIC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CommentSynopticSpecimenLevel]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CommentSynopticSpecimenLevel](
	[SYNOPTIC_ID] [decimal](38, 0) NULL,
	[SYNOPIC_LINE] [int] NULL,
	[SPECIMEN_ID] [decimal](38, 0) NULL,
	[K_SPECIMEN_KEY] [decimal](38, 0) NULL,
	[SPECIMEN_NUM] [varchar](1000) NULL,
	[K_REQUISITION_KEY] [decimal](38, 0) NULL,
	[CASE_NUM] [varchar](1000) NULL,
	[SPECIMEN_LIST] [varchar](1000) NULL,
	[RECORD_CREATION_DT] [datetime] NULL,
	[IS_SPECIMEN_LEVEL] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Index [IX_SSIS_CommentSynopticSpecimenLevel_SYNOPTIC_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IX_SSIS_CommentSynopticSpecimenLevel_SYNOPTIC_ID] ON [SSIS_CommentSynopticSpecimenLevel]
(
	[SYNOPTIC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Table [SSIS_CommentSynopticText]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CommentSynopticText](
	[SYNOPTIC_ID] [decimal](38, 0) NULL,
	[SYNOPTIC_NAME] [varchar](1000) NULL,
	[SPECIMEN_LIST] [varchar](1000) NULL,
	[RECORD_CREATION_DT] [datetime] NULL,
	[INSTANT_OF_UPDATE_DTTM] [datetime] NULL,
	[MISSING_REQ_DATA_YN] [char](1) NULL,
	[HLV_ID] [decimal](38, 0) NULL,
	[ELEMENT_ID] [varchar](1000) NULL,
	[CUR_VALUE_DATETIME] [datetime] NULL,
	[CONTEXT_NAME] [varchar](1000) NULL,
	[CUR_VALUE_SOURCE] [varchar](1000) NULL,
	[RECORD_ID_NUMERIC] [decimal](38, 0) NULL,
	[REC_ARCHIVED_YN] [char](1) NULL,
	[CUR_VAL_UTC_DTTM] [datetime] NULL,
	[ELEM_VALUE_LINE] [decimal](38, 0) NULL,
	[SMRTDTA_ELEM_VALUE] [varchar](max) NULL,
	[ELEM_DESC_LINE] [decimal](38, 0) NULL,
	[SMRTDTA_ELEM_DESC] [varchar](max) NULL,
	[CLA_CON_NAME] [varchar](1000) NULL,
	[ABBREVIATION] [varchar](1000) NULL,
	[DATA_TYPE_C] [decimal](38, 0) NULL,
	[CONCEPT_ID] [varchar](1000) NULL,
	[PARENT_CONCEPT] [varchar](max) NULL,
	[CONCEPT_HIERARCHY] [varchar](max) NULL,
	[RANK_SYNOPTIC] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_SSIS_CommentSynopticText_SYNOPTIC_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IX_SSIS_CommentSynopticText_SYNOPTIC_ID] ON [SSIS_CommentSynopticText]
(
	[SYNOPTIC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_CommentSynopticTextComment]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_CommentSynopticTextComment](
	[HLV_ID] [decimal](38, 0) NULL,
	[LINE] [decimal](38, 0) NULL,
	[CURRENT_COMMENT] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_SSIS_CommentSynopticTextComment_HLV_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IX_SSIS_CommentSynopticTextComment_HLV_ID] ON [SSIS_CommentSynopticTextComment]
(
	[HLV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_ConfigPackage]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_ConfigPackage](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PackageFolderPath] [varchar](500) NOT NULL,
	[PackageFileName] [varchar](500) NOT NULL,
	[Sequence] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_SsisConfigPackage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_ConfigRun]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_ConfigRun](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](1000) NOT NULL,
	[Val] [varchar](4000) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_SSISConfig] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [SSIS_EthnicGroup]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_EthnicGroup](
	[ETHNIC_GROUP_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_EthnicGroup] PRIMARY KEY CLUSTERED 
(
	[ETHNIC_GROUP_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_Gender]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Gender](
	[GENDER_CODE_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_Gender] PRIMARY KEY CLUSTERED 
(
	[GENDER_CODE_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_Interpreter]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Interpreter](
	[ORDER_ID] [decimal](38, 0) NOT NULL,
	[ORD_PROC_DESC] [varchar](500) NULL,
	[RSLTS_INTERPRETER] [varchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[REQUISITION_ID] [decimal](38, 0) NOT NULL,
	[PROCEDURE] [varchar](500) NULL,
	[TYPE] [varchar](500) NULL
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_Lab]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Lab](
	[LAB_ID] [varchar](18) NOT NULL,
	[CM_PHY_OWNER_ID] [varchar](25) NULL,
	[CM_LOG_OWNER_ID] [varchar](25) NULL,
	[LAB_NAME] [varchar](200) NULL,
	[STATUS_C] [decimal](38, 0) NULL,
	[LIVE_STATUS_C] [decimal](38, 0) NULL,
	[RECORD_DELETED_C] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_Lab] PRIMARY KEY CLUSTERED 
(
	[LAB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO




/****** Object:  Table [SSIS_Language]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Language](
	[LANGUAGE_C] [varchar](66) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [varchar](66) NULL,
 CONSTRAINT [PK_SSIS_Language] PRIMARY KEY CLUSTERED 
(
	[LANGUAGE_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [SSIS_LinkedOrder]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_LinkedOrder](
	[REQUISITION_ID] [decimal](38, 0) NULL,
	[CASE_ID] [int] NULL,
	[SPEC_TST_ORDER_ID] [decimal](38, 0) NULL,
	[ORDER_ID] [decimal](38, 0) NULL,
	[ORDER_PROC_ID] [decimal](38, 0) NULL,
	[COMPONENT_ID] [decimal](38, 0) NULL,
	[CASE_NUM] [varchar](1000) NULL,
	[PROC_ID] [decimal](38, 0) NULL,
	[COMP_NAME] [varchar](1000) NULL,
	[COMP_EXTERNAL_NAME] [varchar](1000) NULL,
	[DFLT_UNITS] [varchar](1000) NULL,
	[PROC_DESC] [varchar](1000) NULL,
	[SPEC_NUMBER_RLTD] [varchar](1000) NULL,
	[SPEC_LINE] [int] NULL,
	[SPEC_TEST_LINE] [int] NULL,
	[LINKED_ORD_LINE] [int] NULL,
	[ORD_VALUE] [varchar](4000) NULL,
	[ORD_NUM_VALUE] [decimal](38, 5) NULL,
	[REFERENCE_LOW] [varchar](1000) NULL,
	[REFERENCE_HIGH] [varchar](1000) NULL,
	[REFERENCE_UNIT] [varchar](4000) NULL,
	[ORD_RAW_VALUE] [varchar](1000) NULL,
	[RAW_LOW] [varchar](1000) NULL,
	[RAW_HIGH] [varchar](1000) NULL,
	[REPORTABLE_YN] [char](1000) NULL,
	[LAST_RECV_UTC_DTTM] [datetime] NULL,
	[RESULT_DATE] [datetime] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[ORDER_INST] [datetime] NULL,
	[REVIEW_TIME] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_LinkedOrder_CaseId]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_LinkedOrder_CaseId] ON [SSIS_LinkedOrder]
(
	[CASE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_SSIS_LinkedOrder_REQUISITION_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [idx_SSIS_LinkedOrder_REQUISITION_ID] ON [SSIS_LinkedOrder]
(
	[REQUISITION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Table [SSIS_MatrialStatus]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_MatrialStatus](
	[MARITAL_STATUS_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_MatrialStatus] PRIMARY KEY CLUSTERED 
(
	[MARITAL_STATUS_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_Patient]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Patient](
	[PAT_ID] [varchar](105) NOT NULL,
	[PAT_MRN_ID] [varchar](105) NULL,
	[PAT_EPI_ID] [varchar](256) NULL,
	[PAT_PREFIX_NM] [varchar](256) NULL,
	[PAT_FIRST_NM] [varchar](256) NULL,
	[PAT_LAST_NM] [varchar](256) NULL,
	[PAT_MI_NM] [varchar](508) NULL,
	[PAT_FULL_NM] [varchar](256) NULL,
	[PAT_CITY] [varchar](256) NULL,
	[PAT_STATE] [varchar](256) NULL,
	[PAT_COUNTRY] [varchar](256) NULL,
	[PAT_DOB] [datetime] NULL,
	[Pat_DEATH_DATE] [datetime] NULL,
	[PAT_DECEASED_IND] [int] NULL,
	[PAT_ETHNIC_GROUP_CD] [decimal](38, 0) NULL,
	[PAT_GENDER_CD] [varchar](105) NULL,
	[PAT_LANG_CD] [varchar](105) NULL,
	[PAT_MARITAL_STATUS_CD] [decimal](38, 0) NULL,
	[PAT_RACE_CD] [decimal](38, 0) NULL,
	[PAT_REC_CREATE_DT] [datetime] NULL,
	[Y_OCCUPATION] [varchar](50) NULL,
	[IS_EPICCARE_PAT] [int] NULL,
 CONSTRAINT [PK_SSIS_Patient] PRIMARY KEY CLUSTERED 
(
	[PAT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_PatientRace]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_PatientRace](
	[PATIENT_RACE_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_PatientRace] PRIMARY KEY CLUSTERED 
(
	[PATIENT_RACE_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_Specimen]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Specimen](
	[SPECIMEN_ID] [varchar](18) NOT NULL,
	[LAB_ID] [varchar](18) NULL,
	[SPEC_NUMBER_LN1] [varchar](254) NULL,
	[SPEC_DTM_COLLECTED] [datetime] NULL,
	[SPEC_DTM_RECEIVED] [datetime] NULL,
	[SPEC_SOURCE_C] [decimal](38, 0) NULL,
	[SPEC_COLLECT_BY] [varchar](254) NULL,
	[SPEC_EPT_PAT_ID] [varchar](18) NULL,
	[SPEC_QC_FLAG_YN] [varchar](254) NULL,
	[SPEC_VAL_STAT_C] [decimal](38, 0) NULL,
	[SPEC_CLOSED_DT] [datetime] NULL,
	[SPEC_COLL_BY_ID] [varchar](18) NULL,
	[SPEC_DRAW_TYPE_C] [decimal](38, 0) NULL,
	[CASE_ID] [bigint] NULL,
	[SPEC_DELETED_YN] [varchar](38) NULL,
	[SPEC_COLL_UTC_DTTM] [datetime] NULL,
	[SPEC_RCVD_UTC_DTTM] [datetime] NULL,
	[SPEC_FROZEN_YN] [varchar](38) NULL,
	[AP_RECEIVE_UTC_DTTM] [datetime] NULL,
	[AP_RECEIVED_BY_ID] [varchar](18) NULL,
	[RECV_BY_BARCODE_YN] [varchar](38) NULL,
	[SPECIMEN_TYPE_C] [decimal](38, 0) NULL,
	[COLL_PRTR_OVRIDE_YN] [varchar](38) NULL,
 CONSTRAINT [PK_SSIS_Specimen] PRIMARY KEY CLUSTERED 
(
	[SPECIMEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_SSIS_Specimen_SPECIMEN_ID]    Script Date: 9/10/2025 4:46:58 PM ******/
CREATE NONCLUSTERED INDEX [IX_SSIS_Specimen_SPECIMEN_ID] ON [SSIS_Specimen]
(
	[SPECIMEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_SpecimenDrawType]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_SpecimenDrawType](
	[SPEC_DRAW_TYPE_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_SpecimenDrawType] PRIMARY KEY CLUSTERED 
(
	[SPEC_DRAW_TYPE_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [SSIS_SpecimenSource]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_SpecimenSource](
	[SPECIMEN_SOURCE_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_SpecimenSource] PRIMARY KEY CLUSTERED 
(
	[SPECIMEN_SOURCE_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [SSIS_SpecimenStatus]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_SpecimenStatus](
	[SPEC_VAL_STAT_C] [decimal](38, 0) NOT NULL,
	[NAME] [varchar](254) NULL,
	[TITLE] [varchar](254) NULL,
	[ABBR] [varchar](254) NULL,
	[INTERNAL_ID] [decimal](38, 0) NULL,
 CONSTRAINT [PK_SSIS_SpecimenStatus] PRIMARY KEY CLUSTERED 
(
	[SPEC_VAL_STAT_C] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO




/****** Object:  Table [SSIS_Staff]    Script Date: 9/10/2025 4:46:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SSIS_Staff](
	[K_EMPLOYEE_KEY] [varchar](50) NOT NULL,
	[USER_ID] [varchar](50) NULL,
	[INTERNAL_USER_ID] [varchar](50) NULL,
	[EMPLOYEE_NM] [varchar](200) NULL,
	[EFF_FROM_DT] [datetime] NULL,
	[EFF_TO_DT] [datetime] NULL,
 CONSTRAINT [PK_SSIS_Staff] PRIMARY KEY CLUSTERED 
(
	[K_EMPLOYEE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

